# Generated by Django 4.2.5 on 2023-09-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_countryoforigin_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
