# Generated by Django 4.2.5 on 2023-09-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_productcomment_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ожидает', 'Ожидает'), ('в обработке', 'В обработке'), ('отправлен', 'Отправлен'), ('доставлен', 'Доставлен'), ('отменен', 'Отменен')], max_length=50),
        ),
    ]
