# Generated by Django 4.2.5 on 2023-09-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_remove_order_total_price_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ожидает', 'Ожидает'), ('в обработке', 'В обработке'), ('отправлен', 'Отправлен'), ('доставлен', 'Доставлен'), ('отменен', 'Отменен')], default='ожидает', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='backend_api.OrderProduct', to='backend_api.product'),
        ),
    ]
